name: KillForUP
main: com.gabifur_br.killforup.KillForUP
version: 1.4
api-version: 1.19
commands:
  changelog:
    description: Veja as mudanças do servidor
    usage: /changelog
  mute:
    description: Muta um jogador
    usage: /mute <jogador>
    permission: furry.mute
    permission-message: "Você não tem permissão para mutar jogadores!"
  unmute:
    description: Desmuta um jogador
    usage: /unmute <jogador>
    permission: furry.mute
    permission-message: "Você não tem permissão para desmutar jogadores!"
  status:
    description: Mostra o status do jogador
    usage: /status
    permission: furry.status
    permission-message: "Você não tem permissão para ver o status!"

permissions:
  furry.mute:
    description: Permissão para mutar e desmutar jogadores
    default: op
  furry.status:
    description: Permissão para ver o status do jogador
    default: true
  killforup.admin:
    description: Permissão para administrar o plugin (reload, etc.)
    default: op
